redtI/redTI/core/urls.py
from django.urls import path
from core.views import HomeView

app_name = "core"

urlpatterns = [
    path('', HomeView.as_view(), name="home")
]

redtI/redTI/redTI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settinggs.MEDIA_URL, document_root=settings.MEDIA_ROOT)

redtI/redTI/users/urls.py
from django.urls import path
from users.views import ProfileView, LogoutView, LoginView
app_name = "users"

urlpatterns = [
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'), 
    path('subs/', include('subs.url')),
]

redtI/redTI/templates/base.html
{% load static %}
<html>

<head>
    <title>Rediti</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'imagens/fogo.png' %}">
    <link href = "{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <footer>
        <span>Rediti feito na FAI</span>
    </footer>
</body>

</html>

redtI/redTI/templates/navbar.html
<div class="navbar">
    <a href=""><img src="">Logo aqui</a>
    <div class = "links-area">
        <ul class = links-list>
            <a href="{% url 'core:home' %}"><li>Home</li></a>
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' user.pk %}"><li>Profile</li></a>
                <a href="{% url 'subs:subreditis' %}"><li>Subs</li></a>
                <a href="{% url 'users:logout'%}"><li>Logout</li></a>
            {% else %}
            <a class="nav-link" href="{% url 'users:signup' %}">Cadastro</a> |
                <a href="{% url 'users:login'%}"><li>Login</li></a>
            {% endif %}
        </ul>
    </div>
</div>